[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fc-django-post-api"
version = "2026.6.0"
description = "Django REST API package extracted from fc_django_crazypowertools"
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.10"
authors = [
  {name = "DBox AI"}
]
dependencies = [
    "Django>=3.2,<4.0",
    "djangorestframework>=3.13,<3.15",
    "djangorestframework-simplejwt>=4.8,<6.0",
    "django-filter>=21.0,<23.0",
    "djoser>=2.0",
    "django-tbase-post-product>=2026.3.1617736733,<2027.0.0",
]

[tool.setuptools.packages.find]
where = ["src"]
